const clients = [{
        slug: 'hofp',
        name: 'House of Providence',
        desc: '<p>This amazing organization is revolutionizing foster care in Michigan. Foster youth with low prospects for adoption are allowed to stabilize and heal on their own timeline in a comforting, safe, and familial environment.</p><p>We offer our full range of services to House of Providence, working to maximize their reach and impact for the children they serve by helping them grow and engage with their donor base most effectively.</p>',
        shortD: 'The House of Providence is a permanent home for the foster youth of Michigan. Their goal is to instill hope in minors who have only known the intense instability of the foster care system by allowing them to stabilize and heal in a therapeutic and familial environment.',
        services: [
            'Web, Desktop, and Mobile Application',
            'UI/UX',
            'Conversion Rate Optimization',
            'Creative Direction',
            'Content Strategy',
            'Digital Marketing',
            'SEO',
            'Asset Creation',
            'Digital Communications',
            'Public Relations',
            'Brand Identity',
            'Reputation Management',
        ],
        year: '2019',
        url: 'https://thehofp.org',
        img: '/img/clients/hofp.png',
        gif: 'gif/hofp.gif',
    },
    {
        slug: 'hop-ecom',
        name: 'HOPe Clothing Line',
        desc: '<p>The House of Providence clothing line is a beautiful, 100% ethically sourced brand that benefits children in foster care. HoP is revolutionizing outcomes for these children who have been through so much pain and suffering, giving them hope, healing, and helping them leave the foster care system permanently through adoption.</p><p>We are honored to be able to partner with House of Providence on this project!</p>',
        shortD: 'A new vision for 2019. With over 35 years of experience, PLM is one of the largest concrete and asphalt maintenance companies in Wisconsin.',
        services: [
            'Web, Desktop, and Mobile Application',
            "Ecommerce Setup",
            '',
            'UI/UX',
            'Brand Identity',
            'Creative Direction',
            'Digital Marketing',
        ],
        year: '2021',
        url: 'https://thehofp.org/shop',
        img: '/img/clients/plm.png',
        gif: '/gif/hope.gif',
    }, {
        slug: 'goherear',
        name: 'goHere AR',
        desc: '<p>As computing moves from physical screens to spatial computing, goHere AR creates valuable, easy to use mixed reality applications both for enterprises already using mixed reality as well as forward thinking companies planning to implement it in preparation for consumer mixed reality.</p>',
        shortD: 'A new vision for 2019. With over 35 years of experience, PLM is one of the largest concrete and asphalt maintenance companies in Wisconsin.',
        services: [
            'Web, Desktop, and Mobile Application',
            'UI/UX',
            'Brand Identity',
            'Creative Direction',
            'Digital Marketing',
        ],
        year: '2021',
        url: 'https://mixyourreality.com',
        img: '/img/clients/plm.png',
        gif: '/gif/mym.gif',
    }, {
        slug: 'barnes',
        name: 'Barnes Homebuilders',
        desc: '<p>Founded in 1964, Barnes Homebuilders has been serving central Texas with <b>integrity and loyalty</b> for over half a century.</p><p>goHere brought this established company into the 21st century with a professional web presence, matching their <b>commitment to quality.</b></p>',
        shortD: 'A new vision for 2019. With over 35 years of experience, PLM is one of the largest concrete and asphalt maintenance companies in Wisconsin.',
        services: [
            'Web, Desktop, and Mobile Application',
            'UI/UX',
            'Brand Identity',
            'Creative Direction',
            'Digital Marketing',
        ],
        year: '2011',
        url: 'https://barneshb.com',
        img: '/img/clients/plm.png',
        gif: '/gif/barnes.gif',
    }, {
        slug: 'bedandbarkfest',
        name: 'Bed & Barkfest',
        desc: '<p>It’s hard to find someone you trust to take care of your dog, but Bed & BARKfest makes it easy! Married couple Erin and Justin started a high end dog boarding experience in their home where dogs are treated like family while their owners are away. They receive ample love, human attention, appropriate socialization with other dogs, exercise, and even training!</p><p>We helped them create a dynamic website to support their online store and show visitors why Bed & BARKfest is making pet owner’ s short list!</p>',
        shortD: 'A new vision for 2019. With over 35 years of experience, PLM is one of the largest concrete and asphalt maintenance companies in Wisconsin.',
        services: [
            'Web, Desktop, and Mobile Application',
            'UI/UX',
            'Brand Identity',
            'Creative Direction',
            'Digital Marketing',
        ],
        year: '2021',
        url: 'https://bedandbarkfest.com',
        img: '/img/clients/plm.png',
        gif: '/gif/bedbark.gif',
    }, {
        slug: 'reidchiro',
        name: 'Reid Chiropractic',
        desc: '<p>Dr. Reid is among the top 10 nutritionists in the state of Michigan, and his patients benefit tremendously from his wealth of knowledge and healing hands. Practicing for over 30 years, he continues to educate himself on new discoveries in his field so he’s always on the cutting edge of healthcare for his patients.</p><p>goHere created a brand to represent the level of excellence and care he provides for his patients. </p>',
        shortD: 'A new vision for 2019. With over 35 years of experience, PLM is one of the largest concrete and asphalt maintenance companies in Wisconsin.',
        services: [
            'Web, Desktop, and Mobile Application',
            'UI/UX',
            'Brand Identity',
            'Creative Direction',
            'Digital Marketing',
        ],
        year: '2011',
        url: 'https://reidchiropractic.com',
        img: '/img/clients/plm.png',
        gif: '/gif/reid.gif',
    },
    {
        slug: 'major-goolsbys',
        name: "Major Goolsby's",
        desc: '<p>goHere gave Major Goolsby’s the online identity worthy of the #1 sports bar in Milwaukee.</p><p>With respect for the over 45 years the Major has been serving downtown Milwaukee, we created a fresh new look that enhances their already enormously successful name.</p>',
        shortD: 'The #1 Sports Bar in Milwaukee',
        services: ['UX', 'Visual Design', 'Branding', 'Creative Direction'],
        year: '2018',
        url: 'https://majorgoolsbys.com',
        img: '/img/clients/majors.png',
        gif: '/gif/major.gif',
    }, {
        slug: 'tristar-wellness',
        name: 'Tristar Wellness',
        desc: '<p>Tristar is an extremely versatile cross between a typical doctor’s office and a wellness center. Specializing in pain, addiction, and internal medicine, they emphasize holistic medicine while remaining on the cutting edge of modern medicine.</p><p>We took their web presence to the next level with a beautiful new design, flawless search engine compatibility, and reimagined public relations strategy.</p>',
        shortD: 'The premier chiropractic and nutrition center in Tulsa, OK.',
        services: ['UX', 'Visual Design', 'Branding', 'Creative Direction'],
        year: '2018',
        url: 'https://tristarwell.com',
        img: '/img/clients/divine.png',
        gif: '/gif/tristar.gif',
    },
    {
        slug: 'divine-chiro',
        name: 'Divine Chiropractic',
        desc: '<p>Divine specializes in a one-of-a-kind approach to health focused on the mind-body connection.</p><p>We partnered with Divine to give their brand a completely new look and feel with a web presence, brand identity, and branded assets to match who they are as a company.</p>',
        shortD: 'The premier chiropractic and nutrition center in Tulsa, OK.',
        services: ['UX', 'Visual Design', 'Branding', 'Creative Direction'],
        year: '2018',
        url: 'https://divinechiro.com',
        img: '/img/clients/divine.png',
        gif: '/gif/divine.gif',
    },

    {
        slug: 'bosman-chiro',
        name: 'Bosman Chiropractic',
        desc: '<p>Dr. Bosman is a highly regarded chiropractor and nutritionist who has been serving Eastern Michigan for over 20 years.</p><p>Our expertise in consulting with healthcare practitioners to most effectively market themselves served Dr. Bosman well in creating a brand identity and web presence that promotes his practice.</p>',
        shortD: 'Bosman Chiropractic has been proudly serving the metro Detroit area for over 20 years!',
        services: ['UX', 'Visual Design', 'Branding', 'Creative Direction'],
        year: '2018',
        url: 'https://www.bosmanchiropractic.com/',
        img: '/img/clients/bosman.png',
        gif: '/gif/bosman.gif',
    },

    {
        slug: 'mim',
        name: 'Michigan Intergrative Medicine',
        desc: '<p>Michigan Integrative is a highly respected holistic medicine clinic specializing in Chinese Medicine, fertility, and other holistic options.</p><p>goHere gave them a beautiful new web presence and brand identity, showcasing their practice in a way that attracts new customers.</p>',
        shortD: 'A fertility, holistic medicine, and acupuncture center.',
        services: ['UX', 'Visual Design', 'Branding', 'Creative Direction'],
        year: '2018',
        url: 'https://michiganintegrativemedicine.com/',
        img: '/img/clients/mim.png',
        gif: '/gif/mim.gif',
    },
];

export default clients;